name: "Gutenberg's books"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aad0cd'
    - '#121411'
    - '#696b68'
    - '#7797a0'
  brandStrength: 0.28618661081418395
  lightness: 0.3125
  saturation: 0.9395939244423062
  rhythmicContrast: 0.75
purpose: []
